#version redhat
- name: Instalamos paquetes
  yum: name={{ lista_paquetes_httpd }} state=latest

- name: iniciamos y habilitamos el servicio httpd
  service: name=httpd state=started enabled=true

- firewalld:
    service: https
    permanent: true
    immediate: true
    state: enabled


- firewalld:
    service: http
    permanent: true
    state: enabled
